services:
  - type: static
    name: projet-junior-client
    rootDir: client
    buildCommand: |
      curl -fsSL https://bun.sh/install | bash
      export BUN_INSTALL="$HOME/.bun"
      export PATH="$BUN_INSTALL/bin:$PATH"
      bun run build
    publishPath: dist
    headers:
      - path: "/*"
        values:
          Cache-Control: "public, max-age=0, must-revalidate"
    redirects:
      - source: "/*"
        destination: "/index.html"
        status: 200
