services:
  - type: web
    name: projet-junior-api
    env: node
    plan: free
    buildCommand: cd server && npm install --legacy-peer-deps && npx prisma generate
    startCommand: cd server && npm start
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: "mongodb+srv://cesaristos5:D5NfqTbJGXpybjqL@k2ngrouptest.8xgdo.mongodb.net/test0?retryWrites=true&w=majority&appName=k2ngrouptest"
      - key: ALLOWED_ORIGINS
        value: "https://projet-junior-client.onrender.com"
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: APP_URL
        value: https://projet-junior-client.onrender.com
